### ISSUE TITLE
Fix missing GR secondary structure lines

### ISSUE THREAD

**Issue by AntonPetrov** [Rfam/rfam-3d-seed-alignments#3]
For example, [RF00008-Hammerhead ribozyme (type III)](https://github.com/Rfam/rfam-3d-seed-alignments/blob/master/data/output/RF00008.sto) does not have SS lines for the following IDs:

```
URS000080DE02_32630/1-69
URS000080E0C8_32630/1-12
URS000080DFDA_32630/1-57
URS0000868531_32630/1-48  
```

**Comment by AntonPetrov** [comment]
@nancyontiveros Hi Nancy! Could you please edit the RF00008 SEED and remove these sequences? ☝️

There seems to be an RNAcentral bug that @blakesweeney is aware of. The sequences are already included in the SEED, just with a different taxonomic identifier. 

Also `URS000080E0C8_32630` is only 12 nucleotides long so there is no real value in adding it in the SEED. I will filter out such sequences in the future.

Nancy, please close this issue once you commit the updated alignment. Thanks a lot and sorry about this bug!

**Comment by nancyontiveros** [comment]
I am on it

**Comment by AntonPetrov** [comment]
Thanks Nancy! Just to clarify, I am talking about the following 4 sequences in the seed:
<img width="1168" alt="Screenshot 2022-03-07 at 11 21 54" src="https://user-images.githubusercontent.com/432675/157021973-41ad3f35-5da3-45bd-9081-3a1edaac42ba.png">

**Comment by nancyontiveros** [comment]
I'm confused, from this sequences only URS000080E0C8_32630 does not have an SS line, but the have it. 
<img width="1109" alt="Screenshot 2022-03-07 at 11 24 23" src="https://user-images.githubusercontent.com/59445835/157022379-a48f76db-9115-42e7-9a8a-f7ba384cdece.png">

> For example, [RF00008-Hammerhead ribozyme (type III)](https://github.com/Rfam/rfam-3d-seed-alignments/blob/master/data/output/RF00008.sto) does not have SS lines for the following IDs:
> 
> ```
> URS000080DE02_32630/1-69
> URS000080E0C8_32630/1-12
> URS000080DFDA_32630/1-57
> URS0000868531_32630/1-48  
> ```

**Comment by nancyontiveros** [comment]
[RF00008_SEED.txt](https://github.com/Rfam/rfam-3d-seed-alignments/files/8197281/RF00008_SEED.txt)

**Comment by AntonPetrov** [comment]
The confusion stems from the fact that the Rfam FTP and the website strip out the `#=GR` lines, the rest of the alignment is the same. I created [an issue](https://github.com/Rfam/rfam-production/issues/115) about this.

Let's modify RF00008 as discussed on Slack and close this issue when the alignment is committed ✅🚀
